services:
  mysql:
    image: mysql:8.0.37
    environment:
     - MYSQL_ROOT_PASSWORD=#@&ampY8Do^mWI*4
     - MYSQL_DATABASE=library
     - MYSQL_USER=library
     - MYSQL_PASSWORD=amp*Y8Do
    ports:
     - "3306:3306"
    volumes:
     - ./mysql:/var/lib/mysql:rw
